better styling

diff --git a/.local/bin/extract b/.local/bin/extract
--- a/.local/bin/extract
+++ b/.local/bin/extract
@@ -17,16 +17,41 @@ if [ ! -z "$2" ]; then
 fi
 
 case $1 in
-    *.tar.bz2)   tar xvjf "$1"              ;;
-    *.tar.gz)    tar xvzf "$1" -C "$dest"   ;;
-    *.bz2)       bunzip2 "$1"               ;;
-    *.rar)       unrar x "$1" "$dest"       ;;
-    *.gz)        gunzip "$1"                ;;
-    *.tar)       tar xvf "$1" -C "$dest"    ;;
-    *.tbz2)      tar xvjf "$1"              ;;
-    *.tgz)       tar xvzf "$1"              ;;
-    *.zip)       unzip "$1" -d "$dest"      ;;
-    *.Z)         uncompress "$1"            ;;
-    *.7z)        7z x  "$1"                 ;;
-    *)           echo "extract: $1 can't be extracted" ;;
+    *.tar.bz2)
+        tar xvjf "$1"
+        ;;
+    *.tar.gz)
+        tar xvzf "$1" -C "$dest"
+        ;;
+    *.bz2)
+        bunzip2 "$1"
+        ;;
+    *.rar)
+        unrar x "$1" "$dest"
+        ;;
+    *.gz)
+        gunzip "$1"
+        ;;
+    *.tar)
+        tar xvf "$1" -C "$dest"
+        ;;
+    *.tbz2)
+        tar xvjf "$1"
+        ;;
+    *.tgz)
+        tar xvzf "$1"
+        ;;
+    *.zip)
+        unzip "$1" -d "$dest"
+        ;;
+    *.Z)
+        uncompress "$1"
+        ;;
+    *.7z)
+        7z x  "$1"
+        ;;
+    *)
+        echo "extract: $1 can't be extracted"
+        exit 1
+        ;;
 esac
